language: rust
rust:
  - stable
  - nightly
arch:
  - amd64
  - arm64
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: Aarch64
      os: linux
      arch: arm64
      dist: bionic
    - name: Linux
      os: linux
    - name: MacOS (xcode12)
      os: osx
      osx_image: xcode12
    # - name: Windows (vs2017)
    #   os: windows
script:
  - cd evercrypt-sys
  - cargo build --verbose
  - cargo test --verbose
  - cd ../evercrypt-rs
  - cargo build --verbose
  - cargo test --verbose
